# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2ad785394b4a88c502843839092f6c21345fe5668dc91cfc111270f550824a3574b30c804008ef8e897f041640ba62117210dab186de0330b4aefa62e0d664a

test:
  secret_key_base: 0d8c31fc7805ce92285169a632d4e1f43557f9b424a7b30ed98a7a03b3353b886f389f4aa41ee34a4d2a3d08d97084715c341c1e45d0766eae09c5b72be21673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
